linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - gofumpt
    # deprecated
    - tenv

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  lll:
    line-length: 160
  tagliatelle:
    case:
      rules:
        json: snake
  varnamelen:
    check-return: true
    check-type-param: true
    ignore-names:
      - err
      - tt