version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funcorder
    - wsl
  settings:
    lll:
      line-length: 160
    revive:
      rules:
        - name: blank-imports
          disabled: true
    staticcheck:
      checks:
        - "-QF1008"
    tagliatelle:
      case:
        rules:
          json: snake
    varnamelen:
      check-return: true
      check-type-param: true
      ignore-names:
        - err
        - tt
        - db
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - lll
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(github.com/blueprintue)
        - default
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
