version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funcorder
    - wsl
  settings:
    lll:
      line-length: 160
    staticcheck:
      checks:
        - "-QF1008"
    tagliatelle:
      case:
        rules:
          json: snake
    varnamelen:
      check-return: true
      check-type-param: true
      ignore-names:
        - err
        - tt
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
